build-production:
  image: docker:stable
  # rules: # can limit branches further or add rules for only tags etc...
  #   - if: '$CI_COMMIT_BRANCH == "master"'
  tags:
    - gitlab-org-docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH_SLUG:$CI_COMMIT_BRANCH .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH_SLUG:$CI_COMMIT_BRANCH
